TECHNOLOGIES = [
    "Python",
    "Django",
    "Flask",
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "JavaScript",
    "React",
    "Angular",
    "Vue",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Azure",
    "Linux",
    "Git",
    "CI/CD",
    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Data Science",
    "Pandas",
    "NumPy",
    "Scikit-learn",
]
